declare const L: any;
declare const Plotly: any;
declare const DEFAULT_CENTER: [number, number];
declare const DEFAULT_ZOOM = 8;
declare const MAX_SPAN_DEG = 8;
type VariableKey = 'ndvi' | 'temp' | 'soil';
declare let currentVariable: VariableKey;
declare const map: any;
declare const osmBase: any;
declare const ndviChartContainer: HTMLDivElement | null;
declare const ndviChartDiv: HTMLDivElement | null;
declare function showChartContainer(): void;
declare function hideChartContainer(): void;
declare const drawnItems: any;
declare const drawControl: any;
declare let currentBbox: [number, number, number, number] | null;
declare let activeOverlay: any | null;
declare const startInput: HTMLInputElement | null;
declare const endInput: HTMLInputElement | null;
declare const generateGifButton: HTMLButtonElement | null;
declare const tempStartInput: HTMLInputElement | null;
declare const tempEndInput: HTMLInputElement | null;
declare const generateTempGifButton: HTMLButtonElement | null;
declare const soilStartInput: HTMLInputElement | null;
declare const soilEndInput: HTMLInputElement | null;
declare const generateSoilGifButton: HTMLButtonElement | null;
declare const variableSelect: HTMLSelectElement | null;
declare const ndviControls: HTMLElement | null;
declare const tempControls: HTMLElement | null;
declare const soilControls: HTMLElement | null;
declare const ndviColorbar: any;
declare const tempColorbar: any;
declare const soilColorbar: any;
declare function plotTimeseries(variable: VariableKey, dates: string[], values: number[]): void;
declare function requestGifAndSeries(variable: VariableKey, start: string, end: string, bbox: [number, number, number, number]): Promise<void>;
declare const collapseButton: HTMLButtonElement | null;
declare const restoreButton: HTMLButtonElement | null;
declare const body: HTMLElement;
//# sourceMappingURL=main.d.ts.map